const Lists = [
  {
    id: 1,
    name: "ksl",
    Image: "images/Shoe.jpg",
    price: "2000",
    quantity: 50,
    item: "Loafers",
    rating: "4",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },
  {
    id: 2,
    name: "ksw 01",
    Image: "images/Shoe2.png",
    price: " 2500",
    quantity: 50,
    item: "shoe",
    rating: "4.5",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },

  {
    id: 3,
    name: "royal s 01",
    Image: "images/Shoe2.png",
    price: " 6000",
    quantity: 50,
    item: "Sneaker",
    rating: "5",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },
  {
    id: 5,
    name: "ksl",
    Image: "images/Shoe.jpg",
    price: "2000",
    quantity: 50,
    item: "Loafers",
    rating: "4",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },
  {
    id: 5,
    name: "ksw 01",
    Image: "images/Shoe2.png",
    price: " 2500",
    quantity: 50,
    item: "shoe",
    rating: "4.5",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },

  {
    id: 6,
    name: "royal s 01",
    Image: "images/Shoe2.png",
    price: " 6000",
    quantity: 50,
    item: "Sneaker",
    rating: "5",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },

  {
    id: 7,
    name: "ksl",
    Image: "images/Shoe.jpg",
    price: "2000",
    quantity: 50,
    item: "Loafers",
    rating: "4",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },
  {
    id: 8,
    name: "ksw 01",
    Image: "images/Shoe2.png",
    price: " 2500",
    quantity: 50,
    item: "shoe",
    rating: "4.5",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },

  {
    id: 9,
    name: "royal s 01",
    Image: "images/Shoe2.png",
    price: " 6000",
    quantity: 50,
    item: "Sneaker",
    rating: "5",
    color: { red: true, black: true, white: true, yellow: true, green: true },
  },
];

export default Lists;
